# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_id=iguanatweaksreborn
mod_version=4.2.6
mc_version=1.20.1
forge_version=47.3.22
parchment_version=2023.09.03
mixin_version=0.8.5
lib_version=1.16.1
mpr_version=4.10.14
enhancedai_version=2.5.3
shieldsplus_version=1.10.2
emi_version=1.1.4+1.20.1
pehkui_version=3.8.2
max_health_fix_version=12.0.2
sereneseasons_version=9.1.0.0
glitchcore_version=0.0.1.1