modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.insane96.eu/projects/mods/insanesurvivaloverhaul/"
logoFile="logo.png"
credits="""
IguanaMan for the original Mod.
Effect Icons by hamzaa#1200.
Unfair one shot sound by thecheeseman from freesound.org.
Stamina overlay code from AppleSkin exhaustion code.
Tinkers' Construct 3 for many \"borrowed\" ideas.
Carboniglio for Alpha testing and many ideas.
SonicTakoDrake for playtesting and letting me nerf hoes,
Kurimu for playtesting and letting me nerf fishing.
Dylan M. M. for brainstorming ideas.
kioraSperlusenta for bearing with me in livestream.
e___kho for some durium textures.
"""
authors="${mod_authors}"

description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="insanelib"
    mandatory=true
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="maxhealthfix"
    mandatory=true
    versionRange="[12.0.2,)"
    ordering="NONE"
    side="BOTH"
    [dependencies.${mod_id}.mc-publish]
        modrinth="max-health-fix" # Modrinth's project slug
        curseforge="max-health-fix" # CurseForge's project slug

[[dependencies.${mod_id}]]
    modId="mobspropertiesrandomness"
    mandatory=false
    versionRange="[5.0.0-alpha,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="enhancedai"
    mandatory=false
    versionRange="[2.5.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="shieldsplus"
    mandatory=false
    versionRange="[1.11.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="toolbelt"
    mandatory=false
    versionRange="[1.20.02,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sereneseasons"
    mandatory=false
    versionRange="[9.1.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="pehkui"
    mandatory=false
    versionRange="[3.7.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="globalpacks"
    mandatory=false
    versionRange="[1.16.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="paxi"
    mandatory=false
    versionRange="[1.20-forge-4.0,)"
    ordering="AFTER"
    side="BOTH"